### ISSUE TITLE
Consider using emoji to indicate user input

### ISSUE THREAD

**Issue by james-pcdr** [python-can-define-radio/python-course#22]
Example:

```
Enter your name: 📝 Bob
Hi Bob.
```

If we do this, we should do it in all lessons, PEs, and explain what it means (maybe in prelim).

**Comment by james-pcdr** [comment]
I messed up the branch history by attempting to rebase; need to fix

**Comment by wolverine-is-the-best** [comment]
do not forget we need to merge this branch back to main now that python is over

**Comment by james-pcdr** [comment]
Superseded by #28
