### ISSUE TITLE
Explore Flupy/pipe21

### ISSUE THREAD

**Issue by wolverine-is-the-best** [python-can-define-radio/python-course#31]
Perhaps start with [map](https://flupy.readthedocs.io/en/latest/api.html#flupy.flu.map) and [filter](https://flupy.readthedocs.io/en/latest/api.html#flupy.flu.filter). Then `count(`,  `chunk(`, `flatten(`, `sum(`, `min(`, `max(`.

Then perhaps look at the (ironically more difficult) [Welcome page](https://flupy.readthedocs.io/en/latest/welcome.html)

**Comment by wolverine-is-the-best** [comment]
i cannot find a good tutorial for either of these. not sure how to continue as the docs are just gibberish to me.

**Comment by james-pcdr** [comment]
Roger. Closing for now.
